# Generated by Django 5.2.12 on 2026-03-26 07:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='received_from',
            field=models.CharField(blank=True, help_text='e.g. Solan, H6, Chandigarh', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.category'),
        ),
        migrations.AddField(
            model_name='item',
            name='colour',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='date_recorded',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('RECEIPT', 'Received New (Introduction)'), ('DAMAGE', 'Damaged/Broken'), ('TRANSFER', 'Sent/Transferred')], max_length=20),
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
