# Generated by Django 6.0.3 on 2026-03-26 12:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorytransaction",
            name="date_recorded",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
