# Generated by Django 5.2.8 on 2026-03-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_item_sub_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='current_stock',
            field=models.IntegerField(default=0),
        ),
    ]
