# Generated by Django 5.2.8 on 2026-03-26 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_item_current_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='current_stock',
            new_name='quantity',
        ),
    ]
