# Generated by Django 5.2.8 on 2026-03-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_current_stock_item_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
