# Generated by Django 6.0.3 on 2026-03-26 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_inventorytransaction_date_recorded"),
        ("inventory", "0005_item_remarks"),
    ]

    operations = []
