# Generated by Django 6.0.3 on 2026-03-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_building_image_floor_image_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='remarks',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='remarks',
            field=models.CharField(blank=True, null=True),
        ),
    ]
